# Generated by Django 2.1.5 on 2021-12-19 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_date_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 19, 4, 55, 21, 312908, tzinfo=utc)),
        ),
    ]
