# Generated by Django 2.1.5 on 2021-12-21 12:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211219_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 12, 53, 58, 506833, tzinfo=utc)),
        ),
    ]
