# Generated by Django 2.1.5 on 2021-12-02 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('img', models.TextField(default='URL')),
                ('name', models.CharField(default='Product', max_length=128)),
                ('desc', models.TextField(default='No Description')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['id', 'price', '-price', 'name', '-name'],
            },
        ),
    ]
